### ISSUE TITLE
User configurable error patterns

### ISSUE THREAD

**Issue by jojohans** [NSO-developer/drned-xmnr#109]
We should allow users to specify custom error patterns. This would obviously include all parameters we can set today, including start patter, stop patter, max lines, ...

The patterns we have today should not be automatic since they are XR-specific, not general.

The only exception is the " E " pattern py.test emits.

**Comment by jomiklos** [comment]
Keeping the current internal implementation format for matcher, following seems to be approximate model for user definitions... Comments/change proposals welcome.

```diff
diff --git a/src/yang/drned-xmnr.yang b/src/yang/drned-xmnr.yang
index b5d5381..0d47938 100644
--- a/src/yang/drned-xmnr.yang
+++ b/src/yang/drned-xmnr.yang
@@ -166,6 +166,28 @@ module drned-xmnr {
         }
       }
     }
+
+    list error-patterns {
+      key "match";
+      leaf match {
+        mandatory true;
+        type string;
+      }
+      leaf matcher-type {
+        mandatory true;
+        type enumeration {
+          enum exact;
+          enum terminated;
+        }
+      }
+      leaf terminator {
+        when "../matcher-type = 'terminated'";
+        type string;
+      }
+      leaf max-lines {
+        type uint8;
+      }
+    }
   }

   augment /ncs:devices/ncs:device {
```
