### ISSUE TITLE
Disable a set of states and/or ignore them in walk-states/explore-states

### ISSUE THREAD

**Issue by jojohans** [NSO-developer/drned-xmnr#51]
We need commands to disable states, e.g:
drned-xmnr states  disable-states [ s1 s2 ]

(tags s1 and s2 so that walk-states and explore-states ignore them)

and
drned-xmnr transition walk-states ignore-states [ s1 s2 ]

(like walk-states without arguments)

**Comment by martin-volf** [comment]
`ignore-states` should be fairly straightforward and easy; the only question is what to do in situations like

    drned-xmnr transition walk-states states [ s1 s2 s3 s4 ] ignore-states [ s2 s4 ]

I guess go ahead and do what it seems to mean, i.e. walk-states `[ s1 s3 ]`? Or prevent it through the data model or refuse to perform such action?

For `disable-states` there is currently no supporting structure so some thinking needs to be done where to create it, but still should be easy.

**Comment by jojohans** [comment]
I lean toward letting `walk-states states [ s1 s2 s3 ]` override any disabled states. If you say it on the command line we assume you really mean it.
