### ISSUE TITLE
configuring IP and port in the device driver should not be necessary

### ISSUE THREAD

**Issue by martin-volf** [NSO-developer/drned-xmnr#62]
Device IP address and port are already configured in NSO; the direct CLI actions (convert, reset) can reuse them, or at least the IP address, but they need to be configured separately in the device driver.

**Comment by jojohans** [comment]
I agree that we don't need to configure the IP-address in the driver but how do we know what port the CLI is on?

**Comment by martin-volf** [comment]
Generally it's up to the driver how to use the data passed from XMNR:
 * the netsim driver can use the same calculation that ncs-netsim uses, i.e. if the NETCONF port is 12022, then the CLI port is 10022;
 * XR devices use the same port both for NETCONF and CLI.
If nothing like that works, then the driver needs to use other means, just like until now.
