### ISSUE TITLE
Continue from where we left off

### ISSUE THREAD

**Issue by jojohans** [NSO-developer/drned-xmnr#66]
I’d like to see is support for “continue where I left off”. If we import tests (there’s almost 500 now including the ones I’ve got from XR) and some thing happens halfway through (my VPN goes down, device timeout, unrecoverable error, …) we have to restart from the beginning. It would be great if we we could pass a flag to the import statement, e.g. —continue, to tell xmnr to skip test cases if it’s already imported.

**Comment by martin-volf** [comment]
For import-convert we can modify the boolean flag `overwrite` to accept a third value, e.g. `"skip"`. The name `overwrite` is not ideal, but we should keep backwards compatibility if possible, I guess, and we would also avoid `overwrite=true skip=true`.

**Comment by jomiklos** [comment]
i'm thinking to extend action input parameters to provide either "overwrite" (current bool flag) or "skip-existing" (new bool flag to be added).

will try quick draft implementation...

**Comment by jojohans** [comment]
How about making "skip-existing" the default rather than failing as we do today?

**Comment by jomiklos** [comment]
Imho it sounds reasonable - we can change default behavior without introducing new input parameter.

Then the minor question is whether the opposite - "fail-on-existing" behavior is needed or not (introduce new parameter or just not)...

**Comment by jojohans** [comment]
I don't think so. We're not destroying anything by starting in the middle.

**Comment by martin-volf** [comment]
The default should be very cautious, I think: it might be very confusing for the user that some configs are silently ignored because a state with the same name (but different contents) already exists; and there is no good way how to warn the user that some configs were ignored.
