### ISSUE TITLE
Bad errror reporting from cli2netconf when wrong username/password was given.

### ISSUE THREAD

**Issue by jojohans** [NSO-developer/drned-xmnr#69]
In the drned-xmnr log we have:
<DEBUG> 16-Jul-2021::15:09:14.76 drned-xmnr ncs-dp-1245-drned-xmnr:drned_xmnr-1-usid-77-drned-xmnr: - info Failed to authenticate towards device asr9k: Bad password for local/remote user admin/admin

But the filtering code says:
device driver failed
failure Problems with the device driver: the device driver appears to be broken

**Comment by martin-volf** [comment]
This would probably improve with #62 - username and password would be taken from NSO's configuration, so the problem should be less frequent and/or should appear earlier and be more obvious. Nevertheless, it can be fixed with few small changes, but it requires also a minor change in device drivers.
