### ISSUE TITLE
Create new default-config

### ISSUE THREAD

**Issue by jojohans** [NSO-developer/drned-xmnr#76]
I know I at some point said that is was ok to rely on drned-init created when running the import-convert action as a source for default-config to load on the device.

I think that was a bad idea.

If you after having run the translation, want to run the tests on a different device there won't be any default-config file and the load-default-config action will fail.

We should have an explicit way to create a default config.

**Comment by jomiklos** [comment]
Currently the action `setup-xmnr` is required for other XMNR actions over device to run successfully -> to create supporting directories on XMNR's file system for device, etc., including creation of init. file on device for default config.
This is required when NED/XMNR codebase is updated, or when IP address/port (target device) is changed for the NSO device...

New action to setup default config needs to define source data, plus propagate functionality to device driver.
