### ISSUE TITLE
explore-transitions with identical states fail

### ISSUE THREAD

**Issue by jojohans** [NSO-developer/drned-xmnr#82]
If we have two identical states s1 and s2 and run explore-transitions we get an error in the compare-config after the rollback.

If we test s1 -> s2 we apply s2, NSO notice that there's no change and nothing to commit, we rollback to s1 again and drned-xmnr grabs the last rollback files, applies and commit it and finally runs compare-config and notice that the device state is different than s1.

What seems to happen is that since the states are identical and there is nothing to commit, no rollback file is created. drned-xmnr doesn't know this and applies the last rollback file it can find, which comes from an earlier commit.

**Comment by micnovak** [comment]
Fixed + updated LUX test (PR https://github.com/NSO-developer/drned-xmnr/pull/88 and PR https://github.com/NSO-developer/drned-xmnr/pull/90).
